- hosts: all
  collections:
    - devsec.hardening
  vars:
    github_account: UCL
    github_repo: TLOmodel
    runner_user: gha
    runner_workdir: /mnt/tlo
    ssh_deny_users: "{{ runner_user }}"
    python_version: "3.8"

  tasks:

   - name: create github action user
     become: true
     ansible.builtin.user:
       name: "{{ runner_user }}"
       create_home: yes
       home: "/home/{{ runner_user }}"
       shell: /bin/bash

   - name: add deadsnakes ppa
     become: true
     apt_repository:
       repo: ppa:deadsnakes/ppa
       state: present
       update_cache: yes

   - name: install packages from apt
     become: true
     apt:
       name:
         - acl  # https://github.com/georchestra/ansible/issues/55#issuecomment-651043423
         - "python{{ python_version }}"
         - "python{{ python_version }}-distutils"
         - "python{{ python_version }}-venv"
         - python3-pip
         - glibc-tools
         - git-lfs
       state: present

   - name: "update-alternative select python{{ python_version }} as default"
     become: true
     community.general.alternatives:
       name: python
       path: "/usr/bin/python{{ python_version }}"
       link: /usr/bin/python
       state: selected

   - name: install tox
     become: true
     ansible.builtin.shell: "python{{ python_version }} -m pip install tox"
     args:
       creates: /usr/local/bin/tox

   - name: make /mnt writable by everyone
     become: true
     ansible.builtin.file:
       path: "/mnt"
       state: directory
       mode: '1777'

   - name: run github actions runner role
     with_sequence: count="{{ n_runners }}"
     include_role:
       name: monolithprojects.github_actions_runner
       apply:
         become: yes
     vars:
       runner_dir: "/opt/actions-runner/{{ item }}"
       runner_name: "{{ ansible_hostname }}-{{ item }}"
       runner_extra_config_args: "--work {{ runner_workdir }}/{{ item }}/_work"
       reinstall_runner: no

  roles:
    - ssh_hardening
