from tlo.methods import (
    bladder_cancer,
    breast_cancer,
    cardio_metabolic_disorders,
    care_of_women_during_pregnancy,
    contraception,
    demography,
    depression,
    diarrhoea,
    dx_algorithm_adult,
    dx_algorithm_child,
    enhanced_lifestyle,
    epi,
    epilepsy,
    healthburden,
    healthseekingbehaviour,
    healthsystem,
    hiv,
    labour,
    malaria,
    measles,
    newborn_outcomes,
    oesophagealcancer,
    other_adult_cancers,
    postnatal_supervisor,
    pregnancy_supervisor,
    prostate_cancer,
    symptommanager,
)

module_dependencies = {
    bladder_cancer.BladderCancer: (
        demography.Demography,
        enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    breast_cancer.BreastCancer: (
        demography.Demography,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    cardio_metabolic_disorders.CardioMetabolicDisorders: (
        demography.Demography,
        enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    care_of_women_during_pregnancy.CareOfWomenDuringPregnancy: (
        demography.Demography,
        #enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        #contraception.Contraception,
        #labour.Labour,
        pregnancy_supervisor.PregnancySupervisor,
    ),
    contraception.Contraception: (
        demography.Demography,
        #labour.Labour,
    ),
    demography.Demography: (),
    depression.Depression: (
        demography.Demography,
        enhanced_lifestyle.Lifestyle,
        contraception.Contraception,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    diarrhoea.Diarrhoea: (
        demography.Demography,
        enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    dx_algorithm_adult.DxAlgorithmAdult: (
        #healthsystem.HealthSystem,
        #symptommanager.SymptomManager,
    ),
    dx_algorithm_child.DxAlgorithmChild: (
        #healthsystem.HealthSystem,
        #symptommanager.SymptomManager,
    ),
    enhanced_lifestyle.Lifestyle: {
        demography.Demography,
    },
    epi.Epi: (
        demography.Demography,
        healthsystem.HealthSystem,
    ),
    epilepsy.Epilepsy: (
        demography.Demography,
        healthsystem.HealthSystem,
        #symptommanager.SymptomManager,
    ),
    healthburden.HealthBurden: (
        demography.Demography,
    ),
    healthsystem.HealthSystem: (
        demography.Demography,
    ),
    healthseekingbehaviour.HealthSeekingBehaviour: (
        demography.Demography,
        #enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    hiv.Hiv: (
        demography.Demography,
        enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    labour.Labour: (
        demography.Demography,
        enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        #contraception.Contraception,
        #care_of_women_during_pregnancy.CareOfWomenDuringPregnancy,
        #pregnancy_supervisor.PregnancySupervisor,
        #postnatal_supervisor.PostnatalSupervisor,
    ),
    malaria.Malaria: (
        demography.Demography,
        contraception.Contraception,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    measles.Measles: (
        demography.Demography,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    newborn_outcomes.NewbornOutcomes: (
        demography.Demography,
        #enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
        #labour.Labour,
        #pregnancy_supervisor.PregnancySupervisor,
        #postnatal_supervisor.PostnatalSupervisor,
        #care_of_women_during_pregnancy.CareOfWomenDuringPregnancy,
    ),
    oesophagealcancer.OesophagealCancer: (
        demography.Demography,
        enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    other_adult_cancers.OtherAdultCancer: (
        demography.Demography,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    pregnancy_supervisor.PregnancySupervisor: (
        demography.Demography,
        #enhanced_lifestyle.Lifestyle,
        #contraception.Contraception,
        #labour.Labour,
        #care_of_women_during_pregnancy.CareOfWomenDuringPregnancy,
    ),
    postnatal_supervisor.PostnatalSupervisor: (
        demography.Demography,
        #enhanced_lifestyle.Lifestyle,
        healthsystem.HealthSystem,
        #labour.Labour,
        #care_of_women_during_pregnancy.CareOfWomenDuringPregnancy,
    ),
    prostate_cancer.ProstateCancer: (
        demography.Demography,
        healthsystem.HealthSystem,
        symptommanager.SymptomManager,
    ),
    symptommanager.SymptomManager: (
        demography.Demography,
    ),
}