"""

This file gets the various NCD-related Excel file that contains parameters and prevalence data for NCDs

The file was generated by Mikaela Smit

"""
import shutil

# Import and copy file for hypertension:
shutil.copy('/Users/mc1405/Dropbox/Projects - ongoing/Malawi Project/Thanzi la Onse/04 - Methods Repository/Method_HT.xlsx', '/Users/mc1405/PycharmProjects/TLOmodel/resources/'+"ResourceFile_Method_HT2.xlsx'")

# Import and copy file for hypertension:
shutil.copy('/Users/mc1405/Dropbox/Projects - ongoing/Malawi Project/Thanzi la Onse/04 - Methods Repository/Method_T2DM.xlsx', '/Users/mc1405/PycharmProjects/TLOmodel/resources/'+"ResourceFile_Method_T2DM.xlsx'")
