"""

This file gets the various NCD-related Excel file that contains parameters and prevalence data for NCDs.

This file also contains information on all HSI events relating to hypertension.

The file was generated by Mikaela Smit

"""

# TODO: Check if the filepath needs to be written in more dynamic way

import shutil

# Import and copy file for hypertension:
shutil.copy('/Users/mc1405/Dropbox/Projects - ongoing/Malawi Project/Thanzi la Onse/04 - Methods Repository/Method_HT.xlsx', '/Users/mc1405/PycharmProjects/TLOmodel/resources/'+'ResourceFile_Method_HT.xlsx')

# Import and copy file for hypertension:
shutil.copy('/Users/mc1405/Dropbox/Projects - ongoing/Malawi Project/Thanzi la Onse/04 - Methods Repository/Method_T2DM.xlsx', '/Users/mc1405/PycharmProjects/TLOmodel/resources/'+'ResourceFile_Method_T2DM.xlsx')

a=3; # TODO remove this dummy line. For now file does not fun without adding breakpoint at this line.

