# https://github.com/MonolithProjects/ansible-github_actions_runner
# it runs the gha role multiple times using solution in 
# currently not part of the vagrant/ansible provisioning, need to run after vagrant is up with
---
- name: install gha runner
  hosts: all
  user: gha
  become: yes
  vars:
    - github_account: tamuri
    - github_repo: TLOmodel
    - runner_user: gha
  tasks:
    - name: run github actions runner role
      with_sequence: count="{{ n_runners }}"
      include_role:
        name: monolithprojects.github_actions_runner
      vars:
        runner_dir: "/opt/actions-runner/{{ item }}"
        runner_name: "{{ ansible_hostname }}-{{ item }}"
