#!/usr/bin/env python3

import requests
from pathlib import Path
from itertools import product
import time

# =====================
# CONFIG
# =====================

BASE_NCSS = "https://ds.nccs.nasa.gov/thredds/ncss/grid/AMES/NEX/GDDP-CMIP6"
VERSION = "v2.0"

OUTPUT_DIR = Path("nex_gddp_cmip6_malawi_ncss")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Malawi bounding box
BBOX = {
    "north": -9.36366167,
    "south": -17.12627881,
    "west": 32.67161823,
    "east": 35.91841716
}


MODELS = [
    ("ACCESS-CM2", "r1i1p1f1"),
    ("ACCESS-ESM1-5", "r1i1p1f1"),
    ("CanESM5", "r1i1p1f1"),
    ("CMCC-CM2-SR5", "r1i1p1f1"),
    ("CMCC-ESM2", "r1i1p1f1"),
    ("CNRM-CM6-1", "r1i1p1f2"),
    ("CNRM-ESM2-1", "r1i1p1f1"),
    ("EC-Earth3", "r1i1p1f1"),
    ("EC-Earth3-Veg-LR", "r1i1p1f1"),
    ("GFDL-CM4", "r1i1p1f1"),
    ("GFDL-ESM4", "r1i1p1f1"),
    ("GISS-E2-1-G", "r1i1p1f2"),
    ("HadGEM3-GC31-LL", "r1i1p1f3"),
    ("HadGEM3-GC31-MM", "r1i1p1f3"),
    ("INM-CM4-8", "r1i1p1f1"),
    ("INM-CM5-0", "r1i1p1f1"),
    ("KACE-1-0-G", "r1i1p1f1"),
    ("MIROC-ES2L", "r1i1p1f2"),
    ("MIROC6", "r1i1p1f1"),
    ("MPI-ESM1-2-HR", "r1i1p1f1"),
    ("MPI-ESM1-2-LR", "r1i1p1f1"),
    ("MRI-ESM2-0", "r1i1p1f1"),
    ("NorESM2-LM", "r1i1p1f1"),
    ("NorESM2-MM", "r1i1p1f1"),
    ("TaiESM1", "r1i1p1f1"),
    ("UKESM1-0-LL", "r1i1p1f2"),
]

VARIABLES = ["hurs", "huss", "rlds", "rsds", "sfcWind", "tas", "tasmax", "tasmin"]

SCENARIOS = ["ssp245"]

YEAR_RANGES = {
    "ssp245": range(2025, 2041),
}

# =====================
# HELPERS
# =====================

def ncss_url(model, scenario, variant, variable, year):
    """
    Build NCSS URL exactly as generated by THREDDS NetcdfSubset UI
    """
    filename = f"{variable}_day_{model}_{scenario}_{variant}_gn_{year}_{VERSION}.nc"

    dataset_path = (
        f"{BASE_NCSS}/{model}/{scenario}/{variant}/{variable}/{filename}"
    )

    params = (
        f"?var={variable}"
        f"&north={BBOX['north']}"
        f"&south={BBOX['south']}"
        f"&west={BBOX['west']}"
        f"&east={BBOX['east']}"
        f"&horizStride=1"
        f"&time_start={year}-01-01T12:00:00Z"
        f"&time_end={year}-12-31T12:00:00Z"
        f"&accept=netcdf4"
        f"&addLatLon=true"
    )

    return dataset_path + params


def download(url, out_file):
    out_file.parent.mkdir(parents=True, exist_ok=True)

    r = requests.get(url, stream=True, timeout=300)

    if r.status_code == 404:
        print("  ✗ Not found")
        return False

    r.raise_for_status()

    with open(out_file, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)

    return True


# =====================
# MAIN LOOP
# =====================

for (model, variant), scenario, variable in product(MODELS, SCENARIOS, VARIABLES):
    for year in YEAR_RANGES[scenario]:

        out_dir = OUTPUT_DIR / model / scenario / variable
        out_file = out_dir / f"{variable}_day_{model}_{scenario}_{variant}_gn_{year}_malawi.nc"

        if out_file.exists():
            print(f"✓ Exists: {out_file.name}")
            continue

        url = ncss_url(model, scenario, variant, variable, year)

        print(f"→ {model} {scenario} {variable} {year}")
        print(f"  NCSS: {url}")

        try:
            ok = download(url, out_file)
            if ok:
                print(f"  ✔ Saved {out_file.name}")
        except Exception as e:
            print(f"  ⚠ Error: {e}")

        time.sleep(0.3)  # be polite to the server

print("\nDone.")
