name: Run extra tests on issue or pull-request comments

on:
  issue_comment:
    types:
      - created
      
jobs:

  scaled_sim:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: scaled-sim
      commands: tox -v -e profile
      description: Profiled scale run of model
      timeout-minutes: 8640
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}

  multiple_seed_tests:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: multiple-seed-tests
      commands: |
        tox -v -e py38,report -- pytest --seed 2671936806 3512589365 --cov --cov-report=term-missing -vv tests
      description: Run of tests over multiple seeds
      timeout-minutes: 8640
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}
      
  dummy_job:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: dummy-job
      commands: 'true'
      description: Dummy job for testing workflow
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}