name: Run extra tests on issue or pull-request comments

on:
  issue_comment:
    types:
      - created
      
jobs:

  scaled_sim:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: scaled-sim
      commands: tox -v -e profile
      description: Profiled scale run of model
      timeout-minutes: 8640
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}

  multiple_seed_tests:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: multiple-seed-tests
      commands: |
        tox -v -e py38,report -- pytest --seed 2671936806 3512589365 --cov --cov-report=term-missing -vv tests
      description: Run of tests over multiple seeds
      timeout-minutes: 8640
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}
      
  python311_pandas15_fast_tests:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: python3.11-pandas1.5-fast-tests
      commands: |
        tox -v -e py311-pandas15,report -- pytest --skip-slow --cov --cov-report=term-missing -vv tests
      description: Run of fast tests on Python v3.11 with Pandas v1.5
      timeout-minutes: 8640
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}

  python311_pandas15_all_tests:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: python3.11-pandas1.5-all-tests
      commands: |
        tox -v -e py311-pandas15,report -- pytest --cov --cov-report=term-missing -vv tests
      description: Run of all tests on Python v3.11 with Pandas v1.5
      timeout-minutes: 8640
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}

  python311_pandas20_fast_tests:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: python3.11-pandas2.0-fast-tests
      commands: |
        tox -v -e py311-pandas20,report -- pytest --skip-slow --cov --cov-report=term-missing -vv tests
      description: Run of fast tests on Python v3.11 with Pandas v2.0
      timeout-minutes: 8640
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}

  python311_pandas20_all_tests:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: python3.11-pandas2.0-all-tests
      commands: |
        tox -v -e py311-pandas20,report -- pytest --cov --cov-report=term-missing -vv tests
      description: Run of all tests on Python v3.11 with Pandas v2.0
      timeout-minutes: 8640
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}

  dummy_job:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: self-hosted
      keyword: dummy-job
      commands: 'true'
      description: Dummy job for testing workflow
      application-organization: UCL
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}
