name: Run extra tests on pull-request comments

on:
  issue_comment:
    types:
      - created
      
jobs:

  scaled_sim:
    uses: ./.github/workflows/run-on-pr-comment.yml
    with:
      runs-on: self-hosted
      keyword: scaled-sim
      commands: python -m cProfile src/scripts/profiling/scale_run.py --show-progress-bar --ignore-warnings
      description: Scale run of model
