name: Test

on:
  push:

jobs:
  test:
    name: Test job
    runs-on: ["self-hosted", "profiling"]
    timeout-minutes: 10 # 10 minutes
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
      - name: Test
        run: |
          date
          python3 -c 'bytearray(2 * 1024 * 1024 * 1024); import time; time.sleep(60)'
          date
