name: Tests with unpinned dependencies

on:
  schedule:
    - cron: 0 0 15 * *

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Cache tox
        uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{hashFiles('pyproject.toml') }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: python -m pip install tox
      - name: Run tests
        run: tox -v -e py3-latest -- pytest -n auto -vv tests --skip-slow
