name: Test

on:
  push:

jobs:
  test:
    name: Test job
    runs-on: ["self-hosted", "profiling"]
    timeout-minutes: 3
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
      - name: Test
        shell: python3 {0}
        run: |
          import time
          from datetime import datetime

          print("Hello, world!", flush=True)

          for i in range(10):
              print(str(datetime.now()))
              size = i * 1024 ** 2 * 512
              print(f"I am about to allocate {size / 1024 ** 3} GiB of memory", flush=True)
              a = bytearray(size)
              time.sleep(10)
              a
