name: Test

on:
  push:

jobs:
  test:
    name: Test job
    runs-on: ["self-hosted", "profiling"]
    steps:
      - name: Test
        run: |
          date
          echo "Hello world"
          sleep 7200 # 2 hours
          date
