name: Test

on:
  push:

jobs:
  test:
    name: Test job
    runs-on: ["self-hosted", "profiling"]
    timeout-minutes: 10 # 10 minutes
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
      - name: Test
        shell: python3 {0}
        run: |
          import time

          a = bytearray(1 * 1024 * 1024 * 1024)
          time.sleep(20)
          b = bytearray(2 * 1024 * 1024 * 1024)
          time.sleep(20)
          c = bytearray(3 * 1024 * 1024 * 1024)
          time.sleep(20)
          c = bytearray(4 * 1024 * 1024 * 1024)
          time.sleep(20)
