name: Test

on:
  push:

jobs:
  test:
    name: Test job
    runs-on: ["self-hosted", "profiling"]
    steps:
      - name: Test
        run: |
          date
          echo "Hello world"
          for hour in {0..13}; do
              for min in {0..5}; do
                  python3 -c "import time; time.sleep(600)" # 10 minutes
                  date
              done
          done
