name: Test

on:
  push:

jobs:
  test:
    name: Test job
    runs-on: ["self-hosted", "profiling"]
    timeout-minutes: 3
    steps:
      - name: show /proc/cpuinfo
        run: |
          cat /proc/cpuinfo || true
      - name: show /proc/stat
        run: |
          cat /proc/stat || true
      - name: show /sys/fs/cgroup/cpuset/cpuset.effective_cpus
        run: |
          cat /sys/fs/cgroup/cpuset/cpuset.effective_cpus || true
      - name: show /proc/meminfo
        run: |
          cat /proc/meminfo || true
      - name: show /proc/self/cgroup
        run: |
          cat /proc/self/cgroup || true
      - name: show /sys/fs/cgroup/memory/memory.stat
        run: |
          cat /sys/fs/cgroup/memory/memory.stat || true
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
      - name: Test
        shell: python3 {0}
        run: |
          import time
          from datetime import datetime

          print("Hello, world!", flush=True)

          for i in range(5):
              print(str(datetime.now()))
              size = i * 1024 ** 2 * 512
              print(f"I am about to allocate {size / 1024 ** 3} GiB of memory", flush=True)
              a = bytearray(size)
              time.sleep(10)
              a
